# Generated by Django 4.2.24 on 2025-11-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0007_countrylookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='donor_photos/')),
                ('full_name', models.CharField(blank=True, help_text='Full name for display', max_length=200)),
                ('short_bio', models.CharField(blank=True, help_text='Short bio (max 60 characters)', max_length=60)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('is_profile_private', models.BooleanField(default=False, help_text='Make profile visible only to you')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donors', to='auth_app.countrylookup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_app_donorprofile',
            },
        ),
    ]
