# Generated by Django 5.2.8 on 2025-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_update_country_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='country',
        ),
    ]
