# Generated by Django 4.2.24 on 2025-11-20 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_donationamountoption'),
        ('donor', '0003_update_country_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether this donation is anonymous (hide donor identity)')),
                ('anonymous_name', models.CharField(blank=True, help_text='Name for anonymous donations', max_length=200)),
                ('anonymous_email', models.EmailField(blank=True, help_text='Email for receipt/updates (anonymous donations)', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in USD', max_digits=10)),
                ('donation_type', models.CharField(choices=[('ONE_TIME', 'One-time Donation'), ('MONTHLY', 'Monthly Recurring')], default='ONE_TIME', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (e.g., card, mobile money)', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment gateway transaction ID', max_length=200, null=True, unique=True)),
                ('payment_gateway', models.CharField(blank=True, help_text='Payment gateway used (e.g., Stripe, PayPal, M-Pesa)', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor to patient')),
                ('dedication', models.CharField(blank=True, help_text="Optional dedication (e.g., 'In memory of...')", max_length=200)),
                ('recurring_frequency', models.IntegerField(default=1, help_text='Frequency in months (1=monthly, 3=quarterly, etc.)')),
                ('next_charge_date', models.DateField(blank=True, help_text='Next scheduled charge date for recurring donations', null=True)),
                ('is_recurring_active', models.BooleanField(default=False, help_text='Whether recurring donation is active')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of donor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When donation was successfully completed', null=True)),
                ('donor', models.ForeignKey(blank=True, help_text='Authenticated donor (null for anonymous donations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('parent_donation', models.ForeignKey(blank=True, help_text='Parent donation for recurring payment children', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payments', to='donor.donation')),
                ('patient', models.ForeignKey(blank=True, help_text='Specific patient to donate to (null for general donation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donor_donation',
                'ordering': ['-created_at'],
            },
        ),
        # Removed: RemoveField operation for 'country' field that doesn't exist
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt number for tax purposes', max_length=50, unique=True)),
                ('receipt_url', models.URLField(blank=True, help_text='URL to downloadable PDF receipt')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether receipt email was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donor.donation')),
            ],
            options={
                'db_table': 'donor_donationreceipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to donor)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='donor.donation')),
            ],
            options={
                'db_table': 'donor_donationcomment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-created_at'], name='donor_donat_created_0578ba_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donor_donat_status_7b314d_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', '-created_at'], name='donor_donat_donor_i_8c9556_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['patient', '-created_at'], name='donor_donat_patient_fc1cde_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_id'], name='donor_donat_transac_47f860_idx'),
        ),
    ]
