# Generated by Django 5.2.8 on 2025-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donation_remove_donorprofile_country_donationreceipt_and_more'),
        ('donor', '0004_remove_donorprofile_country'),
    ]

    operations = [
    ]
