# Generated by Django 5.2.8 on 2026-01-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donation_remove_donorprofile_country_donationreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('KES', 'Kenyan Shilling (KSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('ZAR', 'South African Rand (R)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', help_text='Currency of the donation', max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10),
        ),
    ]
