# Generated by Django 5.2.8 on 2026-01-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_merge_20251120_1243'),
        ('donor', '0005_remove_donorprofile_country_donation_currency_and_more'),
    ]

    operations = [
    ]
