# Generated by Django 5.2.8 on 2026-01-04 20:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def set_existing_patient_amounts(apps, schema_editor):
    """Set patient_amount = amount for all existing donations (backward compatibility)"""
    Donation = apps.get_model('donor', 'Donation')
    
    # Update all existing donations: patient_amount = amount, rhci_support_amount = 0
    updated_count = Donation.objects.all().update(
        patient_amount=models.F('amount'),
        rhci_support_amount=Decimal('0.00')
    )
    
    print(f"Updated {updated_count} existing donations with patient_amount = amount")


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_merge_20260102_1446'),
        ('patient', '0008_patientprofile_bill_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='patient_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated to patient funding', max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='rhci_support_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Optional amount to support RHCI operations', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total donation amount (patient_amount + rhci_support_amount)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['rhci_support_amount', 'status'], name='donor_donat_rhci_su_402596_idx'),
        ),
        # Set existing donations' patient_amount = amount
        migrations.RunPython(set_existing_patient_amounts, reverse_code=migrations.RunPython.noop),
    ]
