# Generated by Django 5.2.8 on 2026-02-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_add_donation_split_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent value for RHCI reporting', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used (local currency to USD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for payment failure (if any)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text="Payment gateway's reference ID (e.g., Yellow Card collection_id)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='rate_locked_at',
            field=models.DateTimeField(blank=True, help_text='When exchange rate was locked', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway used (e.g., Stripe, PayPal, M-Pesa, AZAMPAY, YELLOWCARD)', max_length=50),
        ),
    ]
