# Generated by Django 5.2.8 on 2026-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_increase_payment_method_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (e.g., card, mobile money)', max_length=255),
        ),
    ]
