# Generated by Django 4.2.24 on 2025-11-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title', max_length=200)),
                ('description', models.TextField(help_text='Campaign story/description')),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Fundraising goal amount', max_digits=10)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount raised so far', max_digits=10)),
                ('end_date', models.DateField(help_text='Campaign end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL)),
                ('launcher', models.ForeignKey(help_text='User who launched this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaign_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method name (e.g., M-Pesa, Bank Transfer, PayPal)', max_length=100)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=200)),
                ('account_number', models.CharField(help_text='Account/phone number', max_length=200)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (if applicable)', max_length=200)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=50)),
                ('additional_info', models.TextField(blank=True, help_text='Additional payment instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'campaign_paymentmethod',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Update title', max_length=200)),
                ('content', models.TextField(help_text='Update content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
                'db_table': 'campaign_campaignupdate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Campaign photo', upload_to='campaign_photos/')),
                ('caption', models.CharField(blank=True, help_text='Photo caption', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary photo for campaign card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Photo',
                'verbose_name_plural': 'Campaign Photos',
                'db_table': 'campaign_campaignphoto',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Payment methods for this campaign (Set by RHCI admin only)', related_name='campaigns', to='campaign.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='campaign_ca_created_283121_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaign_ca_status_3c4318_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['launcher', '-created_at'], name='campaign_ca_launche_6245cb_idx'),
        ),
    ]
