# Generated by Django 5.2.8 on 2026-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('patient', '0008_patientprofile_bill_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_general_fund',
            field=models.BooleanField(default=False, help_text='True if campaign is for general organization fund, False if for specific patients'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='patients',
            field=models.ManyToManyField(blank=True, help_text='Patients benefiting from this campaign (empty if general fund)', related_name='campaigns', to='patient.patientprofile'),
        ),
    ]
