# Generated by Django 4.2.24 on 2025-11-18 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('PATIENT', 'Patient'), ('DONOR', 'Donor'), ('ADMIN', 'Admin')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_patient_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseTypeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hospital Fees, Medical Staff', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='e.g., hospital-fees, medical-staff', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('country', models.CharField(max_length=100)),
                ('short_description', models.CharField(help_text='Brief summary for card display', max_length=255)),
                ('long_story', models.TextField(help_text='Detailed patient story')),
                ('medical_partner', models.CharField(blank=True, help_text='Hospital/Care center name', max_length=200)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_needed', models.TextField(blank=True, help_text='e.g., Removal of Tumor')),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('funding_required', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount RHCI raises for patient', max_digits=10)),
                ('funding_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_treatment_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total average cost including other contributions', max_digits=10)),
                ('cost_breakdown_notes', models.TextField(blank=True, help_text='Additional notes about cost breakdown')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('FULLY_FUNDED', 'Fully Funded'), ('TREATMENT_COMPLETE', 'Treatment Complete')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost for this expense', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional details about this expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(help_text='Select expense type from lookup', on_delete=django.db.models.deletion.PROTECT, to='auth_app.expensetypelookup')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='auth_app.patientprofile')),
            ],
            options={
                'verbose_name': 'Treatment Cost Breakdown',
                'verbose_name_plural': 'Treatment Cost Breakdowns',
                'ordering': ['expense_type__display_order', 'created_at'],
            },
        ),
    ]
