# Generated by Django 5.2.8 on 2025-11-18 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='donor_photos/')),
                ('full_name', models.CharField(blank=True, help_text='Full name for display', max_length=200)),
                ('short_bio', models.CharField(blank=True, help_text='Short bio (max 60 characters)', max_length=60)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('is_profile_private', models.BooleanField(default=False, help_text='Make profile visible only to you')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
