# Generated by Django 5.2.8 on 2025-11-18 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_donorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROFILE_SUBMITTED', 'Profile Submitted'), ('TREATMENT_SCHEDULED', 'Treatment Scheduled'), ('PROFILE_PUBLISHED', 'Profile Published'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('FUNDING_MILESTONE', 'Funding Milestone Reached'), ('FULLY_FUNDED', 'Fully Funded'), ('TREATMENT_STARTED', 'Treatment Started'), ('TREATMENT_COMPLETE', 'Treatment Complete'), ('UPDATE_POSTED', 'Update Posted'), ('STATUS_CHANGED', 'Status Changed')], max_length=30)),
                ('title', models.CharField(help_text='Event title for display', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like funding amount, location, etc.')),
                ('is_milestone', models.BooleanField(default=False, help_text='Mark important events as milestones')),
                ('is_visible', models.BooleanField(default=True, help_text='Control visibility of this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this event (admin, coordinator, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='auth_app.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Timeline Event',
                'verbose_name_plural': 'Patient Timeline Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_profile', '-created_at'], name='auth_app_pa_patient_e53b5a_idx'), models.Index(fields=['event_type'], name='auth_app_pa_event_t_cef3d1_idx')],
            },
        ),
    ]
