# Generated by Django 5.2.8 on 2025-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_patienttimeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienttimeline',
            options={'ordering': ['created_at'], 'verbose_name': 'Patient Timeline Event', 'verbose_name_plural': 'Patient Timeline Events'},
        ),
        migrations.RemoveIndex(
            model_name='patienttimeline',
            name='auth_app_pa_patient_e53b5a_idx',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this patient on homepage'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AddField(
            model_name='patienttimeline',
            name='event_date',
            field=models.DateField(blank=True, help_text='Scheduled/actual date of event (can be future for TBD events)', null=True),
        ),
        migrations.AddField(
            model_name='patienttimeline',
            name='is_current_state',
            field=models.BooleanField(default=False, help_text='Mark this event as the current state of the patient'),
        ),
        migrations.AddField(
            model_name='patienttimeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='patienttimeline',
            index=models.Index(fields=['patient_profile', 'created_at'], name='auth_app_pa_patient_caa382_idx'),
        ),
    ]
