# Generated by Django 4.2.24 on 2025-11-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_patienttimeline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patienttimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patienttimeline',
            name='patient_profile',
        ),
        migrations.RemoveField(
            model_name='treatmentcostbreakdown',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='treatmentcostbreakdown',
            name='patient_profile',
        ),
        migrations.DeleteModel(
            name='ExpenseTypeLookup',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='PatientTimeline',
        ),
        migrations.DeleteModel(
            name='TreatmentCostBreakdown',
        ),
    ]
