# Generated by Django 4.2.24 on 2025-11-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
