# Generated by Django 4.2.24 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_delete_donorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 country code', max_length=3, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display countries')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is available for selection')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country_lookup',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
