# Generated by Django 5.2.8 on 2026-01-04 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Report title (e.g., 'Q1 2026 Financial Report')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the report')),
                ('document', models.FileField(help_text='Excel or PDF financial report document', upload_to='financial_reports/')),
                ('is_public', models.BooleanField(default=False, help_text='Mark as public for community transparency. Only one report can be public at a time.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
