# Generated by Django 5.2.8 on 2026-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_financialreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='google_doc_url',
            field=models.URLField(blank=True, help_text='Google Doc/Drive link to financial report (optional if document file is uploaded)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='document',
            field=models.FileField(blank=True, help_text='Excel or PDF financial report document (optional if google_doc_url is provided)', null=True, upload_to='financial_reports/'),
        ),
    ]
