# Generated by Django 4.2.24 on 2025-11-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0007_countrylookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTypeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hospital Fees, Medical Staff', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='e.g., hospital-fees, medical-staff', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'db_table': 'auth_app_expensetypelookup',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('country', models.CharField(max_length=100)),
                ('short_description', models.CharField(help_text='Brief summary for card display', max_length=255)),
                ('long_story', models.TextField(help_text='Detailed patient story')),
                ('medical_partner', models.CharField(blank=True, help_text='Hospital/Care center name', max_length=200)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_needed', models.TextField(blank=True, help_text='e.g., Removal of Tumor')),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('funding_required', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount RHCI raises for patient', max_digits=10)),
                ('funding_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_treatment_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total average cost including other contributions', max_digits=10)),
                ('cost_breakdown_notes', models.TextField(blank=True, help_text='Additional notes about cost breakdown')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('FULLY_FUNDED', 'Fully Funded'), ('TREATMENT_COMPLETE', 'Treatment Complete')], default='SUBMITTED', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this patient on homepage')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='auth_app.countrylookup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_app_patientprofile',
            },
        ),
        migrations.CreateModel(
            name='TreatmentCostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost for this expense', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional details about this expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(help_text='Select expense type from lookup', on_delete=django.db.models.deletion.PROTECT, to='patient.expensetypelookup')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Treatment Cost Breakdown',
                'verbose_name_plural': 'Treatment Cost Breakdowns',
                'db_table': 'auth_app_treatmentcostbreakdown',
                'ordering': ['expense_type__display_order'],
            },
        ),
        migrations.CreateModel(
            name='PatientTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROFILE_SUBMITTED', 'Profile Submitted'), ('TREATMENT_SCHEDULED', 'Treatment Scheduled'), ('PROFILE_PUBLISHED', 'Profile Published'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('FUNDING_MILESTONE', 'Funding Milestone Reached'), ('FULLY_FUNDED', 'Fully Funded'), ('TREATMENT_STARTED', 'Treatment Started'), ('TREATMENT_COMPLETE', 'Treatment Complete'), ('UPDATE_POSTED', 'Update Posted'), ('STATUS_CHANGED', 'Status Changed')], max_length=30)),
                ('title', models.CharField(help_text='Event title for display', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like funding amount, location, etc.')),
                ('is_milestone', models.BooleanField(default=False, help_text='Mark important events as milestones')),
                ('is_visible', models.BooleanField(default=True, help_text='Control visibility of this event')),
                ('is_current_state', models.BooleanField(default=False, help_text='Mark this event as the current state of the patient')),
                ('event_date', models.DateField(blank=True, help_text='Scheduled/actual date of event (can be future for TBD events)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this event (admin, coordinator, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Timeline Event',
                'verbose_name_plural': 'Patient Timeline Events',
                'db_table': 'auth_app_patienttimeline',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient_profile', 'created_at'], name='auth_app_pa_patient_caa382_idx'), models.Index(fields=['event_type'], name='auth_app_pa_event_t_cef3d1_idx')],
            },
        ),
    ]
