# Generated by Django 4.2.24 on 2025-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Patient profile photo', null=True, upload_to='patient_photos/'),
        ),
    ]
