# Generated by Django 4.2.24 on 2025-11-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patientprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAmountOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Suggested donation amount', max_digits=10)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this option to donors')),
                ('is_recommended', models.BooleanField(default=False, help_text='Highlight this amount as recommended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_amount_options', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Donation Amount Option',
                'verbose_name_plural': 'Donation Amount Options',
                'db_table': 'patient_donationamountoption',
                'ordering': ['patient_profile', 'display_order', 'amount'],
                'unique_together': {('patient_profile', 'amount')},
            },
        ),
    ]
