# Generated by Django 5.2.8 on 2025-11-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_donationamountoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Patient image', upload_to='patient_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display images (lower numbers first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary/featured image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient_profile', models.ForeignKey(help_text='Patient profile this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Image',
                'verbose_name_plural': 'Patient Images',
                'db_table': 'patient_image',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=xxxxx)', max_length=500)),
                ('video_title', models.CharField(blank=True, help_text='Optional title for the video', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_profile', models.OneToOneField(help_text='Patient profile this video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Video',
                'verbose_name_plural': 'Patient Videos',
                'db_table': 'patient_video',
            },
        ),
    ]
