# Generated by Django 5.2.8 on 2026-01-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientimage_patientvideo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donationamountoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='donationamountoption',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('KES', 'Kenyan Shilling (KSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('ZAR', 'South African Rand (R)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', help_text='Currency for this donation amount', max_length=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='funding_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('KES', 'Kenyan Shilling (KSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('ZAR', 'South African Rand (R)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', help_text='Currency for patient funding', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='donationamountoption',
            unique_together={('patient_profile', 'amount', 'currency')},
        ),
    ]
