# Generated by Django 5.2.8 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_donationamountoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bill_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code for Bill Pay/USSD donations (e.g., JIMMY-2024-001)', max_length=50, null=True, unique=True),
        ),
    ]
